"""Step 9: compile RUN/reports/RESULTS_A1.md from the stats tables (all numbers generated, none typed).

The report is the hand-over document for writing the TGRS manuscript.
"""
from __future__ import annotations

import json

import pandas as pd

from a1_common import D, ensure_dirs, now, read_json, update_status


def tbl(df: pd.DataFrame, cols, fmt=None, max_rows=60) -> str:
    if df is None or not len(df):
        return "_(no rows yet)_\n"
    df = df[[c for c in cols if c in df.columns]].head(max_rows).copy()
    fmt = fmt or {}
    for c in df.columns:
        if c in fmt:
            df[c] = df[c].map(lambda v, f=fmt[c]: f.format(v) if pd.notna(v) else "")
    head = "| " + " | ".join(df.columns) + " |\n|" + "---|" * len(df.columns) + "\n"
    return head + "".join("| " + " | ".join(map(str, r)) + " |\n" for r in df.values)


def rd(name):
    p = D["stats"] / f"{name}.csv"
    try:
        return pd.read_csv(p) if p.exists() else None
    except pd.errors.EmptyDataError:
        return None


def main() -> None:
    ensure_dirs()
    pct = {c: "{:.2%}" for c in ("BA", "lo", "hi", "dC", "dPol", "dPol_lo", "dPol_hi", "BA_O2", "BA_O3", "diff",
                                  "within_O2", "within_O3", "O2_mean", "O3_mean", "O2_uniform", "O3_uniform",
                                  "dC_mean", "dC_lo", "dC_hi", "draw_spread_O2", "dF1", "dF1_lo", "dF1_hi",
                                  "BA_two", "macroF1")}
    pct.update({"p": "{:.4f}", "p_holm": "{:.4f}", "multiplier": "{:.2f}", "M_equiv_O2": "{:.2f}"})
    st = read_json(D["reports"] / "PIPELINE_STATUS.json", {})
    H = read_json(D["stats"] / "HYPOTHESES.json", {})
    prereg = (D["reports"] / "A1_PREREG.sha256").read_text().strip() if (D["reports"] / "A1_PREREG.sha256").exists() else "missing"
    md = [f"# A1 results ({now()})", "", f"Pre-registration SHA-256: `{prereg}`", "",
          "All numbers below are generated by a1_s7_stats.py from experiments/REGISTRY.csv. Do not edit by hand.", "",
          "## Pipeline status", "", "```json", json.dumps(st, indent=1, ensure_ascii=False), "```", "",
          "## E1 budget curves (HGB, primary)", "",
          tbl(rd("T_E1_curve"), ["year", "track", "M", "N", "obs", "BA", "lo", "hi", "macroF1", "n_test"], pct),
          "## Coherence gain dC = BA(O3) - BA(O2), Holm-adjusted across budgets", "",
          tbl(rd("T_E1_deltaC"), ["year", "track", "M", "N", "dC", "lo", "hi", "p", "p_holm", "dPol", "dPol_lo", "dPol_hi"], pct),
          "## Absorption point N*", "", tbl(rd("T_Nstar"), ["year", "track", "Nstar_pairs", "Nstar_scenes", "first_M_below", "rule"]),
          "## Equivalent-scene multiplier", "",
          tbl(rd("T_equivalent_scenes"), ["year", "track", "M", "BA_O3", "M_equiv_O2", "multiplier", "note"], pct),
          "## Equal-cost contrast (O3 at M vs O2 at 1.5 M)", "",
          tbl(rd("T_equal_cost"), ["year", "track", "credits", "O3_M", "O2_M", "BA_O3", "BA_O2", "diff", "lo", "hi", "p"], pct),
          "## Per-class F1 gain (selected budgets)", "",
          tbl((lambda d: d[d.M.isin([1, 2, 4, 9])] if d is not None else None)(rd("T_E1_perclass")),
              ["year", "track", "M", "cls", "F1_O2", "F1_O3", "dF1", "dF1_lo", "dF1_hi"], pct, 120),
          "## E3 date selection (random draws of M pairs out of 9)", "",
          tbl(rd("T_E3_random_draws"), ["year", "track", "M", "n_draws", "O2_mean", "O2_uniform", "draw_spread_O2",
                                        "O3_mean", "dC_mean", "dC_lo", "dC_hi"], pct),
          "## E5 two tracks vs one track (same total pairs)", "",
          tbl(rd("T_E5_two_tracks"), ["year", "M_total", "obs", "BA_two", "BA_T37", "diff_vs_T37", "lo_T37", "hi_T37",
                                      "BA_T88", "diff_vs_T88", "lo_T88", "hi_T88"],
              {**pct, **{k: "{:.2%}" for k in ("BA_T37", "diff_vs_T37", "lo_T37", "hi_T37", "BA_T88", "diff_vs_T88", "lo_T88", "hi_T88")}}),
          "## E9 cross-year transfer", "",
          tbl(rd("T_E9_cross_year"), ["train", "test", "track", "M", "BA_O2", "BA_O3", "dC", "lo", "hi", "within_O2", "within_O3"], pct),
          "## E10 robustness", "",
          tbl(rd("T_E10_robustness"), ["year", "track", "M", "learner", "variant", "BA_O2", "BA_O3", "dC", "lo", "hi"], pct, 120),
          "## E11 controls", "", tbl(rd("T_E11_controls"), ["track", "obs", "control", "n", "BA_mean", "BA_max", "BA_true", "chance"],
                                     {"BA_mean": "{:.2%}", "BA_max": "{:.2%}", "BA_true": "{:.2%}", "chance": "{:.2%}"}),
          "## E2w baseline windows (closure subset B2 + 6-day pilot)", ""]
    e2 = rd("T_E2w_windows")
    md.append(tbl(e2, list(e2.columns), {c: "{:.2%}" for c in e2.columns if c != "window"}) if e2 is not None else "_(no rows yet)_")
    md += ["", "## Pre-registered hypotheses", "", "```json", json.dumps(H, indent=1, default=str), "```", "",
           "## Figures", "", *[f"- figures/{p.name}" for p in sorted(D["fig"].glob("*.png"))]]
    (D["reports"] / "RESULTS_A1.md").write_text("\n".join(md), encoding="utf-8")
    update_status("s9_report", "DONE")


if __name__ == "__main__":
    main()
